// src/pages/FlatDashboard.tsx
import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Card } from "@/components/ui/card";
import { usePersistentStore } from "@/hooks/use-persistence";
import {
  Activity,
  Bot,
  Wifi,
  WifiOff,
  Battery,
  Thermometer,
  Cpu,
  HardDrive,
  Play,
  Pause,
  Square,
  AlertTriangle,
  CheckCircle,
  Clock,
  MapPin,
  Eye,
  Settings,
  Zap,
  Shield,
  TrendingUp,
  Calendar,
  Users,
  Navigation,
  Camera,
  Layers,
  Globe,
  Radio,
  Target,
  Move,
  RotateCcw,
  Home,
  Power,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  Minus,
} from "lucide-react";

export default function FlatDashboard() {
  const { store: dashboardPrefs, updateField } = usePersistentStore(
    "dashboard-preferences",
    {
      robotStatus: "idle" as "idle" | "running" | "paused" | "error",
      selectedView: "overview" as "overview" | "detailed" | "monitoring",
      autoRefresh: true,
    }
  );

  const [currentTime, setCurrentTime] = useState(new Date());
  const [isOnline, setIsOnline] = useState(true);

  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  // Mock real-time data
  const systemStats = {
    cpu: 42 + Math.sin(Date.now() / 10000) * 10,
    memory: 68 + Math.cos(Date.now() / 8000) * 5,
    disk: 73,
    temperature: 45 + Math.sin(Date.now() / 15000) * 3,
    battery: 87 - Math.floor(Date.now() / 100000) % 20,
    uptime: "2d 14h 32m",
    networkLatency: 12 + Math.random() * 8,
  };

  const robotData = {
    position: { 
      x: 2.45 + Math.sin(Date.now() / 5000) * 0.1, 
      y: 1.23 + Math.cos(Date.now() / 6000) * 0.1, 
      rotation: 45 + Math.sin(Date.now() / 4000) * 10 
    },
    speed: 0.5 + Math.sin(Date.now() / 3000) * 0.3,
    lastCommand: "Navigate to Point A",
    activeTasks: 3,
    completedTasks: 28,
    currentTask: "Environmental Scanning",
    taskProgress: 65 + Math.sin(Date.now() / 2000) * 10,
  };

  const sensorData = [
    { name: "LIDAR", status: "active", value: "360°", quality: 98 },
    { name: "Camera", status: "active", value: "1080p", quality: 94 },
    { name: "IMU", status: "active", value: "9-axis", quality: 99 },
    { name: "GPS", status: "active", value: "RTK", quality: 89 },
    { name: "Ultrasonic", status: "active", value: "8 sensors", quality: 92 },
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case "running":
        return "from-emerald-500 to-teal-500";
      case "error":
        return "from-red-500 to-pink-500";
      case "paused":
        return "from-yellow-500 to-orange-500";
      default:
        return "from-blue-500 to-cyan-500";
    }
  };

  const getStatusIcon = () => {
    switch (dashboardPrefs.robotStatus) {
      case "running":
        return Play;
      case "error":
        return AlertTriangle;
      case "paused":
        return Pause;
      default:
        return Square;
    }
  };

  const StatusIcon = getStatusIcon();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-6 text-white">
      {/* Header with Time and Status */}
      <div className="mb-8">
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-3xl p-6 shadow-2xl">
          <div className="flex items-center justify-between">
            <div className="space-y-2">
              <h1 className="text-4xl font-light tracking-tight bg-gradient-to-r from-white via-blue-100 to-cyan-100 bg-clip-text text-transparent">
                Robot Command Center
              </h1>
              <p className="text-slate-400 font-light">
                Autonomous system control and monitoring dashboard
              </p>
            </div>
            
            <div className="flex items-center gap-6">
              {/* Time Display */}
              <div className="text-right">
                <p className="text-2xl font-light text-white">
                  {currentTime.toLocaleTimeString('en-US', { 
                    hour12: false,
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit'
                  })}
                </p>
                <p className="text-sm text-slate-400">
                  {currentTime.toLocaleDateString('en-US', {
                    weekday: 'long',
                    month: 'short',
                    day: 'numeric'
                  })}
                </p>
              </div>

              {/* Online Status */}
              <div className={`flex items-center gap-2 px-4 py-2 rounded-full ${
                isOnline 
                  ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" 
                  : "bg-red-500/10 text-red-400 border border-red-500/20"
              }`}>
                {isOnline ? <Wifi className="w-4 h-4" /> : <WifiOff className="w-4 h-4" />}
                <span className="text-sm font-medium">
                  {isOnline ? "Connected" : "Offline"}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8">
        {/* Robot Status - Large Card */}
        <div className="lg:col-span-8">
          <Card className="bg-white/5 backdrop-blur-xl border border-white/10 p-8 shadow-2xl hover:bg-white/10 transition-all duration-300">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* Robot Visualization */}
              <div className="space-y-6">
                <div className="flex items-center gap-4">
                  <div className={`w-16 h-16 rounded-full bg-gradient-to-br ${getStatusColor(dashboardPrefs.robotStatus)} flex items-center justify-center shadow-lg`}>
                    <StatusIcon className="h-8 w-8 text-white" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-light text-white">DINO-01</h2>
                    <Badge className={`bg-gradient-to-r ${getStatusColor(dashboardPrefs.robotStatus)} text-white border-0`}>
                      {dashboardPrefs.robotStatus.toUpperCase()}
                    </Badge>
                  </div>
                </div>

                {/* Current Task */}
                <div className="bg-white/5 rounded-2xl p-4 border border-white/10">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-slate-400 text-sm">Current Task</span>
                    <span className="text-blue-400 text-sm font-mono">{robotData.taskProgress.toFixed(1)}%</span>
                  </div>
                  <p className="text-white font-medium mb-3">{robotData.currentTask}</p>
                  <Progress 
                    value={robotData.taskProgress} 
                    className="h-2 bg-slate-700"
                  />
                </div>

                {/* Quick Actions */}
                <div className="grid grid-cols-2 gap-3">
                  <Button 
                    onClick={() => updateField("robotStatus", "running")}
                    className="bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white"
                  >
                    <Play className="h-4 w-4 mr-2" />
                    Start
                  </Button>
                  <Button 
                    onClick={() => updateField("robotStatus", "paused")}
                    className="bg-white/10 hover:bg-white/20 border border-white/20 text-white"
                  >
                    <Pause className="h-4 w-4 mr-2" />
                    Pause
                  </Button>
                  <Button 
                    onClick={() => updateField("robotStatus", "idle")}
                    className="bg-white/10 hover:bg-white/20 border border-white/20 text-white"
                  >
                    <Square className="h-4 w-4 mr-2" />
                    Stop
                  </Button>
                  <Button 
                    onClick={() => updateField("robotStatus", "error")}
                    className="bg-gradient-to-r from-red-500 to-pink-500 hover:from-red-600 hover:to-pink-600 text-white"
                  >
                    <AlertTriangle className="h-4 w-4 mr-2" />
                    E-Stop
                  </Button>
                </div>
              </div>

              {/* Robot Data */}
              <div className="space-y-4">
                <h3 className="text-lg font-light text-white mb-4">System Metrics</h3>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                    <div className="flex items-center gap-2 mb-2">
                      <MapPin className="h-4 w-4 text-blue-400" />
                      <span className="text-slate-400 text-sm">Position</span>
                    </div>
                    <p className="text-white font-mono text-sm">
                      X: {robotData.position.x.toFixed(2)}m<br/>
                      Y: {robotData.position.y.toFixed(2)}m<br/>
                      θ: {robotData.position.rotation.toFixed(1)}°
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                    <div className="flex items-center gap-2 mb-2">
                      <Zap className="h-4 w-4 text-green-400" />
                      <span className="text-slate-400 text-sm">Speed</span>
                    </div>
                    <p className="text-white font-mono text-lg">
                      {robotData.speed.toFixed(2)} m/s
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-purple-400" />
                      <span className="text-slate-400 text-sm">Tasks</span>
                    </div>
                    <p className="text-white font-mono">
                      {robotData.activeTasks} active<br/>
                      {robotData.completedTasks} completed
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                    <div className="flex items-center gap-2 mb-2">
                      <Radio className="h-4 w-4 text-cyan-400" />
                      <span className="text-slate-400 text-sm">Network</span>
                    </div>
                    <p className="text-white font-mono text-lg">
                      {systemStats.networkLatency.toFixed(0)}ms
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </div>

        {/* System Health */}
        <div className="lg:col-span-4 space-y-6">
          {/* Battery */}
          <Card className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 shadow-xl hover:bg-white/10 transition-all duration-300">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Battery className="h-5 w-5 text-green-400" />
                <span className="text-white font-medium">Battery</span>
              </div>
              <span className="text-2xl font-light text-white">{systemStats.battery}%</span>
            </div>
            <Progress value={systemStats.battery} className="h-3 bg-slate-700" />
            <p className="text-slate-400 text-sm mt-2">Charging not required</p>
          </Card>

          {/* Temperature */}
          <Card className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 shadow-xl hover:bg-white/10 transition-all duration-300">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Thermometer className="h-5 w-5 text-orange-400" />
                <span className="text-white font-medium">Temperature</span>
              </div>
              <span className="text-2xl font-light text-white">{systemStats.temperature.toFixed(1)}°C</span>
            </div>
            <div className="flex justify-between text-sm text-slate-400">
              <span>Optimal</span>
              <span>Max: 85°C</span>
            </div>
          </Card>

          {/* CPU & Memory */}
          <Card className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 shadow-xl hover:bg-white/10 transition-all duration-300">
            <div className="space-y-4">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <Cpu className="h-4 w-4 text-blue-400" />
                    <span className="text-white text-sm">CPU</span>
                  </div>
                  <span className="text-white text-sm">{systemStats.cpu.toFixed(1)}%</span>
                </div>
                <Progress value={systemStats.cpu} className="h-2 bg-slate-700" />
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <HardDrive className="h-4 w-4 text-purple-400" />
                    <span className="text-white text-sm">Memory</span>
                  </div>
                  <span className="text-white text-sm">{systemStats.memory.toFixed(1)}%</span>
                </div>
                <Progress value={systemStats.memory} className="h-2 bg-slate-700" />
              </div>
            </div>
          </Card>
        </div>
      </div>

      {/* Sensors Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mb-8">
        {sensorData.map((sensor, index) => (
          <Card key={sensor.name} className="bg-white/5 backdrop-blur-xl border border-white/10 p-4 shadow-xl hover:bg-white/10 transition-all duration-300">
            <div className="flex items-center justify-between mb-3">
              <span className="text-white font-medium text-sm">{sensor.name}</span>
              <div className="w-3 h-3 rounded-full bg-emerald-500 shadow-lg"></div>
            </div>
            <p className="text-slate-400 text-xs mb-2">{sensor.value}</p>
            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-400">Quality</span>
              <span className="text-xs font-mono text-emerald-400">{sensor.quality}%</span>
            </div>
          </Card>
        ))}
      </div>

      {/* Quick Navigation */}
      <Card className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 shadow-2xl">
        <h3 className="text-lg font-light text-white mb-4">Quick Navigation</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          {[
            { name: "Sequences", icon: Layers, path: "/sequences" },
            { name: "Terminal", icon: Activity, path: "/terminal" },
            { name: "Cameras", icon: Camera, path: "/cameras" },
            { name: "Navigation", icon: Navigation, path: "/navigation" },
            { name: "Settings", icon: Settings, path: "/settings" },
            { name: "Monitoring", icon: TrendingUp, path: "/system-monitoring" },
          ].map((item) => {
            const IconComponent = item.icon;
            return (
              <Button
                key={item.name}
                variant="ghost"
                className="h-20 bg-white/5 hover:bg-white/10 border border-white/10 flex-col gap-2 text-white"
                onClick={() => window.location.href = item.path}
              >
                <IconComponent className="h-6 w-6" />
                <span className="text-xs">{item.name}</span>
              </Button>
            );
          })}
        </div>
      </Card>
    </div>
  );
}

// src/pages/FlatDashboard.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-6">
    <!-- Header Section -->
    <div class="mb-8">
      <n-card class="tesla-glass-card">
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-4xl font-light tracking-tight bg-gradient-to-r from-white via-blue-100 to-cyan-100 bg-clip-text text-transparent mb-2">
              Robotics Control Center
            </h1>
            <p class="text-slate-400 text-lg font-light">
              Comprehensive autonomous system management and monitoring
            </p>
          </div>
          <div class="flex items-center gap-4">
            <div class="text-right">
              <div class="text-2xl font-light text-white">{{ currentTime }}</div>
              <div class="text-sm text-slate-400">{{ currentDate }}</div>
            </div>
            <div class="w-16 h-16 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-2xl flex items-center justify-center shadow-xl">
              <Zap class="h-8 w-8 text-white" />
            </div>
          </div>
        </div>
      </n-card>
    </div>

    <!-- System Status Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
      <!-- Robot Status -->
      <n-card class="tesla-glass-card hover:scale-105 transition-all duration-300">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-slate-400 text-sm font-medium">Robot Status</p>
            <p class="text-2xl font-light text-white mt-1">Online</p>
            <div class="flex items-center gap-2 mt-2">
              <div class="w-2 h-2 bg-emerald-400 rounded-full animate-pulse" />
              <span class="text-xs text-emerald-400">Connected</span>
            </div>
          </div>
          <div class="h-12 w-12 bg-gradient-to-br from-emerald-500/20 to-green-500/20 rounded-xl flex items-center justify-center">
            <Bot class="h-6 w-6 text-emerald-400" />
          </div>
        </div>
      </n-card>

      <!-- Active Tasks -->
      <n-card class="tesla-glass-card hover:scale-105 transition-all duration-300">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-slate-400 text-sm font-medium">Active Tasks</p>
            <p class="text-2xl font-light text-white mt-1">{{ systemStats.activeTasks }}</p>
            <p class="text-xs text-blue-400 mt-2">{{ systemStats.completedTasks }} completed today</p>
          </div>
          <div class="h-12 w-12 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-xl flex items-center justify-center">
            <Play class="h-6 w-6 text-blue-400" />
          </div>
        </div>
      </n-card>

      <!-- System Health -->
      <n-card class="tesla-glass-card hover:scale-105 transition-all duration-300">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-slate-400 text-sm font-medium">System Health</p>
            <p class="text-2xl font-light text-white mt-1">{{ systemStats.health }}%</p>
            <div class="mt-2">
              <n-progress :percentage="systemStats.health" size="small" color="#10b981" />
            </div>
          </div>
          <div class="h-12 w-12 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-xl flex items-center justify-center">
            <Activity class="h-6 w-6 text-purple-400" />
          </div>
        </div>
      </n-card>

      <!-- Uptime -->
      <n-card class="tesla-glass-card hover:scale-105 transition-all duration-300">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-slate-400 text-sm font-medium">Uptime</p>
            <p class="text-2xl font-light text-white mt-1">{{ systemStats.uptime }}</p>
            <p class="text-xs text-slate-400 mt-2">Since last restart</p>
          </div>
          <div class="h-12 w-12 bg-gradient-to-br from-yellow-500/20 to-orange-500/20 rounded-xl flex items-center justify-center">
            <Clock class="h-6 w-6 text-yellow-400" />
          </div>
        </div>
      </n-card>
    </div>

    <!-- Main Dashboard Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
      <!-- Quick Actions -->
      <div class="lg:col-span-1">
        <n-card class="tesla-glass-card">
          <template #header>
            <h3 class="text-xl font-light text-white">Quick Actions</h3>
          </template>
          <div class="space-y-3">
            <router-link to="/sequences" class="block">
              <div class="flex items-center p-4 bg-white/5 rounded-xl hover:bg-white/10 transition-all duration-300 cursor-pointer">
                <div class="h-10 w-10 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-lg flex items-center justify-center mr-4">
                  <Play class="h-5 w-5 text-blue-400" />
                </div>
                <div>
                  <h4 class="font-medium text-white">Start Sequence</h4>
                  <p class="text-sm text-slate-400">Execute automated tasks</p>
                </div>
                <ChevronRight class="h-5 w-5 text-slate-400 ml-auto" />
              </div>
            </router-link>

            <router-link to="/robot-control" class="block">
              <div class="flex items-center p-4 bg-white/5 rounded-xl hover:bg-white/10 transition-all duration-300 cursor-pointer">
                <div class="h-10 w-10 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-lg flex items-center justify-center mr-4">
                  <Gamepad2 class="h-5 w-5 text-purple-400" />
                </div>
                <div>
                  <h4 class="font-medium text-white">Manual Control</h4>
                  <p class="text-sm text-slate-400">Direct robot operation</p>
                </div>
                <ChevronRight class="h-5 w-5 text-slate-400 ml-auto" />
              </div>
            </router-link>

            <router-link to="/cameras" class="block">
              <div class="flex items-center p-4 bg-white/5 rounded-xl hover:bg-white/10 transition-all duration-300 cursor-pointer">
                <div class="h-10 w-10 bg-gradient-to-br from-green-500/20 to-emerald-500/20 rounded-lg flex items-center justify-center mr-4">
                  <Camera class="h-5 w-5 text-green-400" />
                </div>
                <div>
                  <h4 class="font-medium text-white">Camera Feeds</h4>
                  <p class="text-sm text-slate-400">Monitor visual systems</p>
                </div>
                <ChevronRight class="h-5 w-5 text-slate-400 ml-auto" />
              </div>
            </router-link>

            <router-link to="/system-monitoring" class="block">
              <div class="flex items-center p-4 bg-white/5 rounded-xl hover:bg-white/10 transition-all duration-300 cursor-pointer">
                <div class="h-10 w-10 bg-gradient-to-br from-orange-500/20 to-red-500/20 rounded-lg flex items-center justify-center mr-4">
                  <BarChart3 class="h-5 w-5 text-orange-400" />
                </div>
                <div>
                  <h4 class="font-medium text-white">System Monitor</h4>
                  <p class="text-sm text-slate-400">View system metrics</p>
                </div>
                <ChevronRight class="h-5 w-5 text-slate-400 ml-auto" />
              </div>
            </router-link>
          </div>
        </n-card>
      </div>

      <!-- System Metrics -->
      <div class="lg:col-span-2">
        <n-card class="tesla-glass-card">
          <template #header>
            <h3 class="text-xl font-light text-white">System Performance</h3>
          </template>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <!-- CPU Usage -->
            <div class="text-center">
              <div class="relative w-24 h-24 mx-auto mb-4">
                <svg class="w-24 h-24 transform -rotate-90" viewBox="0 0 100 100">
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="rgba(255,255,255,0.1)"
                    stroke-width="8"
                    fill="none"
                  />
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="url(#cpuGradient)"
                    stroke-width="8"
                    stroke-linecap="round"
                    fill="none"
                    :stroke-dasharray="`${metrics.cpu * 2.51} 251`"
                    class="transition-all duration-500"
                  />
                  <defs>
                    <linearGradient id="cpuGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" style="stop-color:#3b82f6" />
                      <stop offset="100%" style="stop-color:#06b6d4" />
                    </linearGradient>
                  </defs>
                </svg>
                <div class="absolute inset-0 flex items-center justify-center">
                  <span class="text-xl font-light text-white">{{ metrics.cpu }}%</span>
                </div>
              </div>
              <h4 class="font-medium text-white">CPU Usage</h4>
              <p class="text-sm text-slate-400">Processing Load</p>
            </div>

            <!-- Memory Usage -->
            <div class="text-center">
              <div class="relative w-24 h-24 mx-auto mb-4">
                <svg class="w-24 h-24 transform -rotate-90" viewBox="0 0 100 100">
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="rgba(255,255,255,0.1)"
                    stroke-width="8"
                    fill="none"
                  />
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="url(#memoryGradient)"
                    stroke-width="8"
                    stroke-linecap="round"
                    fill="none"
                    :stroke-dasharray="`${metrics.memory * 2.51} 251`"
                    class="transition-all duration-500"
                  />
                  <defs>
                    <linearGradient id="memoryGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" style="stop-color:#8b5cf6" />
                      <stop offset="100%" style="stop-color:#d946ef" />
                    </linearGradient>
                  </defs>
                </svg>
                <div class="absolute inset-0 flex items-center justify-center">
                  <span class="text-xl font-light text-white">{{ metrics.memory }}%</span>
                </div>
              </div>
              <h4 class="font-medium text-white">Memory</h4>
              <p class="text-sm text-slate-400">RAM Usage</p>
            </div>

            <!-- Network -->
            <div class="text-center">
              <div class="relative w-24 h-24 mx-auto mb-4">
                <svg class="w-24 h-24 transform -rotate-90" viewBox="0 0 100 100">
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="rgba(255,255,255,0.1)"
                    stroke-width="8"
                    fill="none"
                  />
                  <circle
                    cx="50"
                    cy="50"
                    r="40"
                    stroke="url(#networkGradient)"
                    stroke-width="8"
                    stroke-linecap="round"
                    fill="none"
                    :stroke-dasharray="`${(100 - metrics.latency) * 2.51} 251`"
                    class="transition-all duration-500"
                  />
                  <defs>
                    <linearGradient id="networkGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" style="stop-color:#10b981" />
                      <stop offset="100%" style="stop-color:#06b6d4" />
                    </linearGradient>
                  </defs>
                </svg>
                <div class="absolute inset-0 flex items-center justify-center">
                  <span class="text-xl font-light text-white">{{ metrics.latency }}ms</span>
                </div>
              </div>
              <h4 class="font-medium text-white">Network</h4>
              <p class="text-sm text-slate-400">Latency</p>
            </div>
          </div>
        </n-card>
      </div>
    </div>

    <!-- Recent Activity -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <!-- Recent Tasks -->
      <n-card class="tesla-glass-card">
        <template #header>
          <h3 class="text-xl font-light text-white">Recent Tasks</h3>
        </template>
        <div class="space-y-3">
          <div
            v-for="task in recentTasks"
            :key="task.id"
            class="flex items-center justify-between p-3 bg-white/5 rounded-lg hover:bg-white/10 transition-colors"
          >
            <div class="flex items-center gap-3">
              <div :class="[
                'w-2 h-2 rounded-full',
                task.status === 'completed' ? 'bg-emerald-400' :
                task.status === 'running' ? 'bg-blue-400' :
                task.status === 'failed' ? 'bg-red-400' : 'bg-yellow-400'
              ]" />
              <div>
                <h4 class="font-medium text-white text-sm">{{ task.name }}</h4>
                <p class="text-xs text-slate-400">{{ task.type }}</p>
              </div>
            </div>
            <div class="text-right">
              <n-tag :type="getStatusTagType(task.status)" size="small">
                {{ task.status }}
              </n-tag>
              <p class="text-xs text-slate-400 mt-1">{{ formatTime(task.timestamp) }}</p>
            </div>
          </div>
        </div>
      </n-card>

      <!-- System Logs -->
      <n-card class="tesla-glass-card">
        <template #header>
          <h3 class="text-xl font-light text-white">System Logs</h3>
        </template>
        <n-scrollbar style="max-height: 300px">
          <div class="space-y-2">
            <div
              v-for="(log, index) in systemLogs"
              :key="index"
              class="flex gap-3 p-2 rounded-lg hover:bg-white/5 transition-colors"
            >
              <span class="text-xs font-mono text-slate-400 w-16 flex-shrink-0">{{ log.time }}</span>
              <span :class="[
                'text-xs font-medium w-12 flex-shrink-0',
                log.level === 'INFO' ? 'text-blue-400' :
                log.level === 'WARN' ? 'text-yellow-400' :
                log.level === 'ERROR' ? 'text-red-400' : 'text-green-400'
              ]">
                {{ log.level }}
              </span>
              <span class="text-xs text-slate-300 flex-1">{{ log.message }}</span>
            </div>
          </div>
        </n-scrollbar>
      </n-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import {
  Zap,
  Bot,
  Play,
  Activity,
  Clock,
  Gamepad2,
  Camera,
  BarChart3,
  ChevronRight
} from 'lucide-vue-next'

const currentTime = ref('')
const currentDate = ref('')
let timeInterval: number

const systemStats = ref({
  activeTasks: 3,
  completedTasks: 12,
  health: 94,
  uptime: '5d 14h'
})

const metrics = ref({
  cpu: 45,
  memory: 62,
  latency: 23
})

const recentTasks = ref([
  {
    id: '1',
    name: 'Security Patrol',
    type: 'navigation',
    status: 'completed',
    timestamp: new Date(Date.now() - 300000)
  },
  {
    id: '2',
    name: 'Object Detection',
    type: 'ai',
    status: 'running',
    timestamp: new Date(Date.now() - 60000)
  },
  {
    id: '3',
    name: 'Sensor Calibration',
    type: 'sensor',
    status: 'completed',
    timestamp: new Date(Date.now() - 1800000)
  }
])

const systemLogs = ref([
  { time: '14:32:15', level: 'INFO', message: 'System initialization completed successfully' },
  { time: '14:31:42', level: 'INFO', message: 'ROS node connections established' },
  { time: '14:31:15', level: 'WARN', message: 'High CPU usage detected, optimizing processes' },
  { time: '14:30:58', level: 'SUCCESS', message: 'All sensors operational and calibrated' },
  { time: '14:30:12', level: 'INFO', message: 'Network connection stable, latency 23ms' }
])

const getStatusTagType = (status: string) => {
  switch (status) {
    case 'completed': return 'success'
    case 'running': return 'info'
    case 'failed': return 'error'
    case 'paused': return 'warning'
    default: return 'default'
  }
}

const formatTime = (date: Date) => {
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  
  if (diff < 60000) {
    return 'Just now'
  } else if (diff < 3600000) {
    return `${Math.floor(diff / 60000)}m ago`
  } else {
    return `${Math.floor(diff / 3600000)}h ago`
  }
}

const updateTime = () => {
  const now = new Date()
  currentTime.value = now.toLocaleTimeString()
  currentDate.value = now.toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}

const updateMetrics = () => {
  // Simulate real-time metrics updates
  metrics.value.cpu = Math.floor(Math.random() * 30) + 40
  metrics.value.memory = Math.floor(Math.random() * 20) + 55
  metrics.value.latency = Math.floor(Math.random() * 20) + 15
}

onMounted(() => {
  updateTime()
  timeInterval = setInterval(() => {
    updateTime()
    updateMetrics()
  }, 1000)
})

onUnmounted(() => {
  if (timeInterval) {
    clearInterval(timeInterval)
  }
})
</script>

<style scoped>
.tesla-glass-card {
  background: rgba(255, 255, 255, 0.05) !important;
  backdrop-filter: blur(20px) !important;
  border: 1px solid rgba(255, 255, 255, 0.1) !important;
  border-radius: 20px !important;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25) !important;
}
</style>
