// src/pages/Sensors.tsx
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Activity,
  Camera,
  Radar,
  Thermometer,
  Gauge,
  Compass,
} from "lucide-react";

const Sensors = () => {
  const sensorData = [
    {
      name: "LiDAR",
      type: "sensor_msgs/LaserScan",
      status: "active",
      rate: "10 Hz",
      icon: Radar,
      value: "360° scan",
      health: 95,
    },
    {
      name: "IMU",
      type: "sensor_msgs/Imu",
      status: "active",
      rate: "100 Hz",
      icon: Compass,
      value: "0.02° precision",
      health: 98,
    },
    {
      name: "RGB Camera",
      type: "sensor_msgs/Image",
      status: "active",
      rate: "30 Hz",
      icon: Camera,
      value: "1920x1080",
      health: 87,
    },
    {
      name: "Temperature",
      type: "sensor_msgs/Temperature",
      status: "active",
      rate: "1 Hz",
      icon: Thermometer,
      value: "42°C",
      health: 92,
    },
    {
      name: "Ultrasonic",
      type: "sensor_msgs/Range",
      status: "warning",
      rate: "20 Hz",
      icon: Activity,
      value: "0.5m range",
      health: 75,
    },
    {
      name: "Pressure",
      type: "sensor_msgs/FluidPressure",
      status: "active",
      rate: "5 Hz",
      icon: Gauge,
      value: "1013 hPa",
      health: 89,
    },
  ];

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-4xl font-extralight bg-gradient-to-r from-foreground via-foreground/80 to-foreground/60 bg-clip-text text-transparent">
            Sensor Monitoring
          </h1>
          <p className="text-muted-foreground font-light mt-2">
            Real-time sensor data and health monitoring
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Badge className="bg-blue-100 text-blue-700">
            <Activity className="h-3 w-3 mr-1" />
            8 Sensors
          </Badge>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {sensorData.map((sensor, index) => (
          <Card key={index} className="p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <sensor.icon className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold">{sensor.name}</h3>
                  <p className="text-sm text-muted-foreground">{sensor.type}</p>
                </div>
              </div>
              <Badge
                variant={sensor.status === "active" ? "default" : "destructive"}
                className="gap-1"
              >
                <div
                  className={`ros-status-indicator ${sensor.status === "active" ? "ros-status-active" : "ros-status-error"}`}
                />
                {sensor.status}
              </Badge>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Rate:</span>
                <span className="font-mono">{sensor.rate}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Value:</span>
                <span className="font-mono">{sensor.value}</span>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Health:</span>
                  <span className="font-mono">{sensor.health}%</span>
                </div>
                <Progress value={sensor.health} className="h-2" />
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default Sensors;

// src/pages/Sensors.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-6">
    <div class="mb-8">
      <n-card class="tesla-glass-card">
        <h1 class="text-4xl font-light tracking-tight bg-gradient-to-r from-white via-blue-100 to-cyan-100 bg-clip-text text-transparent">
          Sensor Management
        </h1>
        <p class="text-slate-400 font-light mt-2">
          Multi-sensor data monitoring and calibration
        </p>
      </n-card>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <n-card v-for="sensor in sensors" :key="sensor.id" class="tesla-glass-card">
        <template #header>
          <div class="flex items-center justify-between">
            <h3 class="text-lg font-light text-white">{{ sensor.name }}</h3>
            <n-tag :type="getSensorStatusType(sensor.status)" size="small">
              {{ sensor.status }}
            </n-tag>
          </div>
        </template>
        <div class="space-y-4">
          <div class="flex items-center justify-center py-8">
            <component :is="sensor.icon" class="h-12 w-12 text-slate-400" />
          </div>
          <div class="space-y-2">
            <div class="flex justify-between text-sm">
              <span class="text-slate-400">Type:</span>
              <span class="text-white">{{ sensor.type }}</span>
            </div>
            <div class="flex justify-between text-sm">
              <span class="text-slate-400">Range:</span>
              <span class="text-white">{{ sensor.range }}</span>
            </div>
            <div class="flex justify-between text-sm">
              <span class="text-slate-400">Accuracy:</span>
              <span class="text-white">{{ sensor.accuracy }}</span>
            </div>
          </div>
          <div v-if="sensor.status === 'active'" class="pt-2">
            <div class="text-xs text-slate-400 mb-1">Signal Strength</div>
            <n-progress :percentage="sensor.signal" size="small" />
          </div>
        </div>
      </n-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Radar, Camera, Thermometer, Compass, Zap, Wifi } from 'lucide-vue-next'

const sensors = ref([
  {
    id: 1,
    name: 'LIDAR Scanner',
    type: 'Distance',
    status: 'active',
    range: '0-100m',
    accuracy: '±2cm',
    signal: 95,
    icon: Radar
  },
  {
    id: 2,
    name: 'RGB Camera',
    type: 'Visual',
    status: 'active',
    range: '0-50m',
    accuracy: '1080p',
    signal: 87,
    icon: Camera
  },
  {
    id: 3,
    name: 'Temperature',
    type: 'Environmental',
    status: 'inactive',
    range: '-40°C to 85°C',
    accuracy: '±0.5°C',
    signal: 0,
    icon: Thermometer
  },
  {
    id: 4,
    name: 'IMU Sensor',
    type: 'Orientation',
    status: 'active',
    range: '360°',
    accuracy: '±0.1°',
    signal: 92,
    icon: Compass
  },
  {
    id: 5,
    name: 'Ultrasonic',
    type: 'Proximity',
    status: 'error',
    range: '0-4m',
    accuracy: '±3mm',
    signal: 0,
    icon: Zap
  },
  {
    id: 6,
    name: 'WiFi Module',
    type: 'Communication',
    status: 'active',
    range: '100m',
    accuracy: '802.11ac',
    signal: 78,
    icon: Wifi
  }
])

const getSensorStatusType = (status: string) => {
  switch (status) {
    case 'active': return 'success'
    case 'inactive': return 'warning'
    case 'error': return 'error'
    default: return 'default'
  }
}
</script>

<style scoped>
.tesla-glass-card {
  background: rgba(255, 255, 255, 0.05) !important;
  backdrop-filter: blur(20px) !important;
  border: 1px solid rgba(255, 255, 255, 0.1) !important;
  border-radius: 20px !important;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25) !important;
}
</style>
